#include "marked_pinyin.h"
#include "mandarin.h"
#include "map"
namespace cphonetic
{
using namespace msound;

TokenDict<tuple<INIT, MED, TONE> > MarkedPinyin::_miDict = {
	{"b", TUP( B, KAI, NEUTRAL )}, {"p", TUP( P, KAI, NEUTRAL )},
	{"m", TUP( M, KAI, NEUTRAL )}, {"f", TUP( F, KAI, NEUTRAL )}, {"v", TUP( V, KAI, NEUTRAL )},
	{"d", TUP( D, KAI, NEUTRAL )}, {"t", TUP( T, KAI, NEUTRAL )},
	{"n", TUP( N, KAI, NEUTRAL )}, {"l", TUP( L, KAI, NEUTRAL )},
	{"g", TUP( G, KAI, NEUTRAL )}, {"k", TUP( K, KAI, NEUTRAL )},
	{"ng", TUP( NG, KAI, NEUTRAL )}, {"h", TUP( H, KAI, NEUTRAL )},
	{"zh", TUP( J, KAI, NEUTRAL )}, {"ch", TUP( CH, KAI, NEUTRAL )},
	{"sh", TUP( SH, KAI, NEUTRAL )}, {"r", TUP( R, KAI, NEUTRAL )},
	{"z", TUP( TZ, KAI, NEUTRAL )}, {"c", TUP( TS, KAI, NEUTRAL )}, {"s", TUP( S, KAI, NEUTRAL )},

	{"bi", TUP( B, I, NEUTRAL )}, {"pi", TUP( P, I, NEUTRAL )}, {"mi", TUP( M, I, NEUTRAL )},
	{"fi",TUP(F,I,NEUTRAL)},
	{"di", TUP( D, I, NEUTRAL )}, {"ti", TUP( T, I, NEUTRAL )},
	{"ni", TUP( N, I, NEUTRAL )}, {"li", TUP( L, I, NEUTRAL )},
	{"ji", TUP( G, I, NEUTRAL )}, {"qi", TUP( K, I, NEUTRAL )},
	{"gni", TUP( NG, I, NEUTRAL )}, {"xi", TUP( H, I, NEUTRAL )},
	{"zyi", TUP( TZ, I, NEUTRAL )}, {"cyi", TUP( TS, I, NEUTRAL )}, {"syi", TUP( S, I, NEUTRAL )},
	{"y", TUP( Void, I, NEUTRAL )}, {"yi", TUP( Void, I, NEUTRAL )},
	{"bu", TUP( B, U, NEUTRAL )}, {"pu", TUP( P, U, NEUTRAL )}, {"mu", TUP( M, U, NEUTRAL )}, {"fu", TUP( F, U, NEUTRAL )}, {"vu", TUP( V, U, NEUTRAL )},
	{"du", TUP( D, U, NEUTRAL )}, {"tu", TUP( T, U, NEUTRAL )}, {"nu", TUP( N, U, NEUTRAL )}, {"lu", TUP( L, U, NEUTRAL )},
	{"gu", TUP( G, U, NEUTRAL )}, {"ku", TUP( K, U, NEUTRAL )},
	{"ngu", TUP( NG, U, NEUTRAL )}, {"hu", TUP( H, U, NEUTRAL )},
	{"zhu", TUP( J, U, NEUTRAL )}, {"chu", TUP( CH, U, NEUTRAL )}, {"shu", TUP( SH, U, NEUTRAL )},
	{"ru", TUP( R, U, NEUTRAL )},
	{"zu", TUP( TZ, U, NEUTRAL )}, {"cu", TUP( TS, U, NEUTRAL )}, {"su", TUP( S, U, NEUTRAL )},
	{"w", TUP( Void, U, NEUTRAL )}, {"wu", TUP( Void, U, NEUTRAL )},
	{"nü", TUP( N, IU, NEUTRAL )}, {"lü", TUP( L, IU, NEUTRAL )},
	{"ju", TUP( G, IU, NEUTRAL )}, {"qu", TUP( K, IU, NEUTRAL )},
	{"gnu", TUP( NG, IU, NEUTRAL )}, {"xu", TUP( H, IU, NEUTRAL )},
	{"zü", TUP( TZ, IU, NEUTRAL )}, {"cü", TUP( TS, IU, NEUTRAL )}, {"sü", TUP( S, IU, NEUTRAL )},
	{"yu", TUP( Void, IU, NEUTRAL )},
	//use magic value to substitute the final y for zhy chy shy ry zy cy sy
	{"zhi", TUP( J, MMAGIC, NEUTRAL )}, {"chi", TUP( CH, MMAGIC, NEUTRAL )},
	{"shi", TUP( SH, MMAGIC, NEUTRAL )}, {"ri", TUP( R, MMAGIC, NEUTRAL )},
	{"zi", TUP( TZ, MMAGIC, NEUTRAL )}, {"ci", TUP( TS, MMAGIC, NEUTRAL )}, {"si", TUP( S, MMAGIC, NEUTRAL )},


	{"bī", TUP( B, I, DARK )}, {"pī", TUP( P, I, DARK )}, {"mī", TUP( M, I, DARK )},
	{"fī",TUP(F,I,DARK)},
	{"dī", TUP( D, I, DARK )}, {"tī", TUP( T, I, DARK )},
	{"nī", TUP( N, I, DARK )}, {"lī", TUP( L, I, DARK )},
	{"jī", TUP( G, I, DARK )}, {"qī", TUP( K, I, DARK )},
	{"gnī", TUP( NG, I, DARK )}, {"xī", TUP( H, I, DARK )},
	{"zyī", TUP( TZ, I, DARK )}, {"cyī", TUP( TS, I, DARK )}, {"syī", TUP( S, I, DARK )},
	{"yī", TUP( Void, I, DARK )},
	{"bū", TUP( B, U, DARK )}, {"pū", TUP( P, U, DARK )}, {"mū", TUP( M, U, DARK )}, {"fū", TUP( F, U, DARK )}, {"vū", TUP( V, U, DARK )},
	{"dū", TUP( D, U, DARK )}, {"tū", TUP( T, U, DARK )}, {"nū", TUP( N, U, DARK )}, {"lū", TUP( L, U, DARK )},
	{"gū", TUP( G, U, DARK )}, {"kū", TUP( K, U, DARK )},
	{"ngū", TUP( NG, U, DARK )}, {"hū", TUP( H, U, DARK )},
	{"zhū", TUP( J, U, DARK )}, {"chū", TUP( CH, U, DARK )}, {"shū", TUP( SH, U, DARK )},
	{"rū", TUP( R, U, DARK )},
	{"zū", TUP( TZ, U, DARK )}, {"cū", TUP( TS, U, DARK )}, {"sū", TUP( S, U, DARK )},
	{"wū", TUP( Void, U, DARK )},
	{"nǖ", TUP( N, IU, DARK )}, {"lǖ", TUP( L, IU, DARK )},
	{"jū", TUP( G, IU, DARK )}, {"qū", TUP( K, IU, DARK )},
	{"gnū", TUP( NG, IU, DARK )}, {"xū", TUP( H, IU, DARK )},
	{"zǖ", TUP( TZ, IU, DARK )}, {"cǖ", TUP( TS, IU, DARK )}, {"sǖ", TUP( S, IU, DARK )},
	{"yū", TUP( Void, IU, DARK )},

	{"zhī", TUP( J, MMAGIC, DARK )}, {"chī", TUP( CH, MMAGIC, DARK )},
	{"shī", TUP( SH, MMAGIC, DARK )}, {"rī", TUP( R, MMAGIC, DARK )},
	{"zī", TUP( TZ, MMAGIC, DARK )}, {"cī", TUP( TS, MMAGIC, DARK )}, {"sī", TUP( S, MMAGIC, DARK )},


	{"bí", TUP( B, I, LIGHT )}, {"pí", TUP( P, I, LIGHT )}, {"mí", TUP( M, I, LIGHT )},
	{"fí",TUP(F,I,LIGHT)},
	{"dí", TUP( D, I, LIGHT )}, {"tí", TUP( T, I, LIGHT )},
	{"ní", TUP( N, I, LIGHT )}, {"lí", TUP( L, I, LIGHT )},
	{"jí", TUP( G, I, LIGHT )}, {"qí", TUP( K, I, LIGHT )},
	{"gní", TUP( NG, I, LIGHT )}, {"xí", TUP( H, I, LIGHT )},
	{"zyí", TUP( TZ, I, LIGHT )}, {"cyí", TUP( TS, I, LIGHT )}, {"syí", TUP( S, I, LIGHT )},
	{"yí", TUP( Void, I, LIGHT )},
	{"bú", TUP( B, U, LIGHT )}, {"pú", TUP( P, U, LIGHT )}, {"mú", TUP( M, U, LIGHT )}, {"fú", TUP( F, U, LIGHT )}, {"vú", TUP( V, U, LIGHT )},
	{"dú", TUP( D, U, LIGHT )}, {"tú", TUP( T, U, LIGHT )}, {"nú", TUP( N, U, LIGHT )}, {"lú", TUP( L, U, LIGHT )},
	{"gú", TUP( G, U, LIGHT )}, {"kú", TUP( K, U, LIGHT )},
	{"ngú", TUP( NG, U, LIGHT )}, {"hú", TUP( H, U, LIGHT )},
	{"zhú", TUP( J, U, LIGHT )}, {"chú", TUP( CH, U, LIGHT )}, {"shú", TUP( SH, U, LIGHT )},
	{"rú", TUP( R, U, LIGHT )},
	{"zú", TUP( TZ, U, LIGHT )}, {"cú", TUP( TS, U, LIGHT )}, {"sú", TUP( S, U, LIGHT )},
	{"wú", TUP( Void, U, LIGHT )},
	{"nǘ", TUP( N, IU, LIGHT )}, {"lǘ", TUP( L, IU, LIGHT )},
	{"jú", TUP( G, IU, LIGHT )}, {"qú", TUP( K, IU, LIGHT )},
	{"gnú", TUP( NG, IU, LIGHT )}, {"xú", TUP( H, IU, LIGHT )},
	{"zǘ", TUP( TZ, IU, LIGHT )}, {"cǘ", TUP( TS, IU, LIGHT )}, {"sǘ", TUP( S, IU, LIGHT )},
	{"yú", TUP( Void, IU, LIGHT )},

	{"zhí", TUP( J, MMAGIC, LIGHT )}, {"chí", TUP( CH, MMAGIC, LIGHT )},
	{"shí", TUP( SH, MMAGIC, LIGHT )}, {"rí", TUP( R, MMAGIC, LIGHT )},
	{"zí", TUP( TZ, MMAGIC, LIGHT )}, {"cí", TUP( TS, MMAGIC, LIGHT )}, {"sí", TUP( S, MMAGIC, LIGHT )},


	{"bǐ", TUP( B, I, RISING )}, {"pǐ", TUP( P, I, RISING )}, {"mǐ", TUP( M, I, RISING )},
	{"fǐ",TUP(F,I,RISING)},
	{"dǐ", TUP( D, I, RISING )}, {"tǐ", TUP( T, I, RISING )},
	{"nǐ", TUP( N, I, RISING )}, {"lǐ", TUP( L, I, RISING )},
	{"jǐ", TUP( G, I, RISING )}, {"qǐ", TUP( K, I, RISING )},
	{"gnǐ", TUP( NG, I, RISING )}, {"xǐ", TUP( H, I, RISING )},
	{"zyǐ", TUP( TZ, I, RISING )}, {"cyǐ", TUP( TS, I, RISING )}, {"syǐ", TUP( S, I, RISING )},
	{"yǐ", TUP( Void, I, RISING )},
	{"bǔ", TUP( B, U, RISING )}, {"pǔ", TUP( P, U, RISING )}, {"mǔ", TUP( M, U, RISING )}, {"fǔ", TUP( F, U, RISING )}, {"vǔ", TUP( V, U, RISING )},
	{"dǔ", TUP( D, U, RISING )}, {"tǔ", TUP( T, U, RISING )}, {"nǔ", TUP( N, U, RISING )}, {"lǔ", TUP( L, U, RISING )},
	{"gǔ", TUP( G, U, RISING )}, {"kǔ", TUP( K, U, RISING )},
	{"ngǔ", TUP( NG, U, RISING )}, {"hǔ", TUP( H, U, RISING )},
	{"zhǔ", TUP( J, U, RISING )}, {"chǔ", TUP( CH, U, RISING )}, {"shǔ", TUP( SH, U, RISING )},
	{"rǔ", TUP( R, U, RISING )},
	{"zǔ", TUP( TZ, U, RISING )}, {"cǔ", TUP( TS, U, RISING )}, {"sǔ", TUP( S, U, RISING )},
	{"wǔ", TUP( Void, U, RISING )},
	{"nǚ", TUP( N, IU, RISING )}, {"lǚ", TUP( L, IU, RISING )},
	{"jǔ", TUP( G, IU, RISING )}, {"qǔ", TUP( K, IU, RISING )},
	{"gnǔ", TUP( NG, IU, RISING )}, {"xǔ", TUP( H, IU, RISING )},
	{"zǚ", TUP( TZ, IU, RISING )}, {"cǚ", TUP( TS, IU, RISING )}, {"sǚ", TUP( S, IU, RISING )},
	{"yǔ", TUP( Void, IU, RISING )},

	{"zhǐ", TUP( J, MMAGIC, RISING )}, {"chǐ", TUP( CH, MMAGIC, RISING )},
	{"shǐ", TUP( SH, MMAGIC, RISING )}, {"rǐ", TUP( R, MMAGIC, RISING )},
	{"zǐ", TUP( TZ, MMAGIC, RISING )}, {"cǐ", TUP( TS, MMAGIC, RISING )}, {"sǐ", TUP( S, MMAGIC, RISING )},


	{"bì", TUP( B, I, DEPARTING )}, {"pì", TUP( P, I, DEPARTING )}, {"mì", TUP( M, I, DEPARTING )},
	{"fì",TUP(F,I,DEPARTING)},
	{"dì", TUP( D, I, DEPARTING )}, {"tì", TUP( T, I, DEPARTING )},
	{"nì", TUP( N, I, DEPARTING )}, {"lì", TUP( L, I, DEPARTING )},
	{"jì", TUP( G, I, DEPARTING )}, {"qì", TUP( K, I, DEPARTING )},
	{"gnì", TUP( NG, I, DEPARTING )}, {"xì", TUP( H, I, DEPARTING )},
	{"zyì", TUP( TZ, I, DEPARTING )}, {"cyì", TUP( TS, I, DEPARTING )}, {"syì", TUP( S, I, DEPARTING )},
	{"yì", TUP( Void, I, DEPARTING )},
	{"bù", TUP( B, U, DEPARTING )}, {"pù", TUP( P, U, DEPARTING )}, {"mù", TUP( M, U, DEPARTING )}, {"fù", TUP( F, U, DEPARTING )}, {"vù", TUP( V, U, DEPARTING )},
	{"dù", TUP( D, U, DEPARTING )}, {"tù", TUP( T, U, DEPARTING )}, {"nù", TUP( N, U, DEPARTING )}, {"lù", TUP( L, U, DEPARTING )},
	{"gù", TUP( G, U, DEPARTING )}, {"kù", TUP( K, U, DEPARTING )},
	{"ngù", TUP( NG, U, DEPARTING )}, {"hù", TUP( H, U, DEPARTING )},
	{"zhù", TUP( J, U, DEPARTING )}, {"chù", TUP( CH, U, DEPARTING )}, {"shù", TUP( SH, U, DEPARTING )},
	{"rù", TUP( R, U, DEPARTING )},
	{"zù", TUP( TZ, U, DEPARTING )}, {"cù", TUP( TS, U, DEPARTING )}, {"sù", TUP( S, U, DEPARTING )},
	{"wù", TUP( Void, U, DEPARTING )},
	{"nǜ", TUP( N, IU, DEPARTING )}, {"lǜ", TUP( L, IU, DEPARTING )},
	{"jù", TUP( G, IU, DEPARTING )}, {"qù", TUP( K, IU, DEPARTING )},
	{"gnù", TUP( NG, IU, DEPARTING )}, {"xù", TUP( H, IU, DEPARTING )},
	{"zǜ", TUP( TZ, IU, DEPARTING )}, {"cǜ", TUP( TS, IU, DEPARTING )}, {"sǜ", TUP( S, IU, DEPARTING )},
	{"yù", TUP( Void, IU, DEPARTING )},

	{"zhì", TUP( J, MMAGIC, DEPARTING )}, {"chì", TUP( CH, MMAGIC, DEPARTING )},
	{"shì", TUP( SH, MMAGIC, DEPARTING )}, {"rì", TUP( R, MMAGIC, DEPARTING )},
	{"zì", TUP( TZ, MMAGIC, DEPARTING )}, {"cì", TUP( TS, MMAGIC, DEPARTING )}, {"sì", TUP( S, MMAGIC, DEPARTING )},

};

TokenDict<pair<FIN, TONE> > MarkedPinyin::_mfDict( {
	{"a", {A, NEUTRAL}}, {"o", {O, NEUTRAL}}, {"e", {E, NEUTRAL}}, {"ê", {EH, NEUTRAL}}, {"er", {EL, NEUTRAL}},
	{"r", {EL, NEUTRAL}},
	{"ai", {AI, NEUTRAL}}, {"ei", {EI, NEUTRAL}}, {"i", {EI, NEUTRAL}}, {"ao", {AU, NEUTRAL}}, {"ou", {OU, NEUTRAL}},
	{"u", {OU, NEUTRAL}},
	{"an", {AN, NEUTRAL}}, {"en", {EN, NEUTRAL}}, {"ang", {ANG, NEUTRAL}}, {"eng", {ENG, NEUTRAL}},
	{"am", {AM, NEUTRAL}}, {"em", {EM, NEUTRAL}}, {"n", {EN, NEUTRAL}}, {"ng", {ENG, NEUTRAL}}, {"m", {EM, NEUTRAL}},
	//magic value
	{"ong", {Y, NEUTRAL}},

	{"ā", {A, DARK}}, {"ō", {O, DARK}}, {"ē", {E, DARK}}, {"ê¯", {EH, DARK}}, {"ēr", {EL, DARK}},
	{"āi", {AI, DARK}}, {"ēi", {EI, DARK}}, {"ī", {EI, DARK}}, {"āo", {AU, DARK}}, {"ōu", {OU, DARK}}, {"ū", {OU, DARK}},
	{"ān", {AN, DARK}}, {"ēn", {EN, DARK}}, {"āng", {ANG, DARK}}, {"ēng", {ENG, DARK}}, {"ām", {AM, DARK}},
	{"ēm", {EM, DARK}},
	{"ōng", {Y, DARK}},

	{"á", {A, LIGHT}}, {"ó", {O, LIGHT}}, {"é", {E, LIGHT}}, {"ê´", {EH, LIGHT}}, {"ér", {EL, LIGHT}},
	{"ái", {AI, LIGHT}}, {"éi", {EI, LIGHT}}, {"í", {EI, LIGHT}}, {"áo", {AU, LIGHT}}, {"óu", {OU, LIGHT}}, {"ú", {OU, LIGHT}},
	{"án", {AN, LIGHT}}, {"én", {EN, LIGHT}}, {"áng", {ANG, LIGHT}}, {"éng", {ENG, LIGHT}}, {"ám", {AM, LIGHT}},
	{"ém", {EM, LIGHT}},
	{"óng", {Y, LIGHT}},

	{"ǎ", {A, RISING}}, {"ǒ", {O, RISING}}, {"ě", {E, RISING}}, {"êˇ", {EH, RISING}}, {"ěr", {EL, RISING}},
	{"ǎi", {AI, RISING}}, {"ěi", {EI, RISING}}, {"ǐ", {EI, RISING}}, {"ǎo", {AU, RISING}}, {"ǒu", {OU, RISING}}, {"ǔ", {OU, RISING}},
	{"ǎn", {AN, RISING}}, {"ěn", {EN, RISING}}, {"ǎng", {ANG, RISING}}, {"ěng", {ENG, RISING}}, {"ǎm", {AM, RISING}},
	{"ěm", {EM, RISING}},
	{"ǒng", {Y, RISING}},

	{"à", {A, DEPARTING}}, {"ò", {O, DEPARTING}}, {"è", {E, DEPARTING}}, {"ê`", {EH, DEPARTING}}, {"èr", {EL, DEPARTING}},
	{"ài", {AI, DEPARTING}}, {"èi", {EI, DEPARTING}}, {"ì", {EI, DEPARTING}}, {"ào", {AU, DEPARTING}}, {"òu", {OU, DEPARTING}}, {"ù", {OU, DEPARTING}},
	{"àn", {AN, DEPARTING}}, {"èn", {EN, DEPARTING}}, {"àng", {ANG, DEPARTING}}, {"èng", {ENG, DEPARTING}}, {"àm", {AM, DEPARTING}},
	{"èm", {EM, DEPARTING}},
	{"òng", {Y, DEPARTING}},

	{"ah", {A, ENTERING}}, {"oh", {O, ENTERING}}, {"eh", {E, ENTERING}}, {"êh", {EH, ENTERING}},
	{"h", {ZERO, ENTERING}},

} );


vector<cchar*> MarkedPinyin::_ui = {"ī", "í", "ǐ", "ì", "", "i"};
vector<cchar*> MarkedPinyin::_iu = {"ū", "ú", "ǔ", "ù", "", "u"};
map<INIT, cchar*> MarkedPinyin::_miTrans = {
	{Void, ""},
	{B, "b"},
	{P, "p"},
	{M, "m"},
	{F, "f"},
	{V, "v"},
	{D, "d"},
	{T, "t"},
	{N, "n"},
	{L, "l"},
	{G, "g"},
	{K, "k"},
	{NG, "ng"},
	{H, "h"},
	{J, "zh"},
	{CH, "ch"},
	{SH, "sh"},
	{R, "r"},
	{TZ, "z"},
	{TS, "c"},
	{S, "s"},
};
map<INIT, cchar*> MarkedPinyin::_specInit = {
	{G, "j"}, {K, "q"}, {NG, "gn"}, {H, "x"}, {TZ, "zy"}, {TS, "cy"}, {S, "sy"},
};
map<pair<RIME, TONE>, cchar*> MarkedPinyin::_m0Trans( {
	{{I_, NEUTRAL}, "yi"}, {{IA, NEUTRAL}, "ya"}, {{IE, NEUTRAL}, "ye"}, {{IO, NEUTRAL}, "yo"},
	{{IAI, NEUTRAL}, "yai"}, {{IAU, NEUTRAL}, "yao"}, {{IOU, NEUTRAL}, "you"},
	{{IAN, NEUTRAL}, "yan"}, {{IN, NEUTRAL}, "yin"}, {{IANG, NEUTRAL}, "yang"}, {{ING, NEUTRAL}, "ying"},
	{{IAM, NEUTRAL}, "yam"}, {{IM, NEUTRAL}, "yim"},
	{{U_, NEUTRAL}, "wu"}, {{UA, NEUTRAL}, "wa"}, {{UO, NEUTRAL}, "wo"},
	{{UAI, NEUTRAL}, "wai"}, {{UEI, NEUTRAL}, "wei"}, {{UAN, NEUTRAL}, "wan"}, {{UN, NEUTRAL}, "wen"}, {{UANG, NEUTRAL}, "wang"}, {{ONG, NEUTRAL}, "weng"},
	{{IU_, NEUTRAL}, "yu"}, {{IUO, NEUTRAL}, "yuo"}, {{IUE, NEUTRAL}, "yue"}, {{IUAN, NEUTRAL}, "yuan"}, {{IUN, NEUTRAL}, "yun"}, {{IONG, NEUTRAL}, "yong"},

	{{I_, DARK}, "yī"}, {{IA, DARK}, "yā"}, {{IE, DARK}, "yē"}, {{IO, DARK}, "yō"},
	{{IAI, DARK}, "yāi"}, {{IAU, DARK}, "yāo"}, {{IOU, DARK}, "yōu"},
	{{IAN, DARK}, "yān"}, {{IN, DARK}, "yīn"}, {{IANG, DARK}, "yāng"}, {{ING, DARK}, "yīng"},
	{{IAM, DARK}, "yām"}, {{IM, DARK}, "yīm"},
	{{U_, DARK}, "wū"}, {{UA, DARK}, "wā"}, {{UO, DARK}, "wō"},
	{{UAI, DARK}, "wāi"}, {{UEI, DARK}, "wēi"}, {{UAN, DARK}, "wān"}, {{UN, DARK}, "wēn"}, {{UANG, DARK}, "wāng"}, {{ONG, DARK}, "wēng"},
	{{IU_, DARK}, "yū"}, {{IUO, DARK}, "yuō"}, {{IUE, DARK}, "yuē"}, {{IUAN, DARK}, "yuān"}, {{IUN, DARK}, "yūn"}, {{IONG, DARK}, "yōng"},

	{{I_, LIGHT}, "yí"}, {{IA, LIGHT}, "yá"}, {{IE, LIGHT}, "yé"}, {{IO, LIGHT}, "yó"},
	{{IAI, LIGHT}, "yái"}, {{IAU, LIGHT}, "yáo"}, {{IOU, LIGHT}, "yóu"},
	{{IAN, LIGHT}, "yán"}, {{IN, LIGHT}, "yín"}, {{IANG, LIGHT}, "yáng"}, {{ING, LIGHT}, "yíng"},
	{{IAM, LIGHT}, "yám"}, {{IM, LIGHT}, "yím"},
	{{U_, LIGHT}, "wú"}, {{UA, LIGHT}, "wá"}, {{UO, LIGHT}, "wó"},
	{{UAI, LIGHT}, "wái"}, {{UEI, LIGHT}, "wéi"}, {{UAN, LIGHT}, "wán"}, {{UN, LIGHT}, "wén"}, {{UANG, LIGHT}, "wáng"}, {{ONG, LIGHT}, "wéng"},
	{{IU_, LIGHT}, "yú"}, {{IUO, LIGHT}, "yuó"}, {{IUE, LIGHT}, "yué"}, {{IUAN, LIGHT}, "yuán"}, {{IUN, LIGHT}, "yún"}, {{IONG, LIGHT}, "yóng"},

	{{I_, RISING}, "yǐ"}, {{IA, RISING}, "yǎ"}, {{IE, RISING}, "yě"}, {{IO, RISING}, "yǒ"},
	{{IAI, RISING}, "yǎi"}, {{IAU, RISING}, "yǎo"}, {{IOU, RISING}, "yǒu"},
	{{IAN, RISING}, "yǎn"}, {{IN, RISING}, "yǐn"}, {{IANG, RISING}, "yǎng"}, {{ING, RISING}, "yǐng"},
	{{IAM, RISING}, "yǎm"}, {{IM, RISING}, "yǐm"},
	{{U_, RISING}, "wǔ"}, {{UA, RISING}, "wǎ"}, {{UO, RISING}, "wǒ"},
	{{UAI, RISING}, "wǎi"}, {{UEI, RISING}, "wěi"}, {{UAN, RISING}, "wǎn"}, {{UN, RISING}, "wěn"}, {{UANG, RISING}, "wǎng"}, {{ONG, RISING}, "wěng"},
	{{IU_, RISING}, "yǔ"}, {{IUO, RISING}, "yuǒ"}, {{IUE, RISING}, "yuě"}, {{IUAN, RISING}, "yuǎn"}, {{IUN, RISING}, "yǔn"}, {{IONG, RISING}, "yǒng"},

	{{I_, DEPARTING}, "yì"}, {{IA, DEPARTING}, "yà"}, {{IE, DEPARTING}, "yè"}, {{IO, DEPARTING}, "yò"},
	{{IAI, DEPARTING}, "yài"}, {{IAU, DEPARTING}, "yào"}, {{IOU, DEPARTING}, "yòu"},
	{{IAN, DEPARTING}, "yàn"}, {{IN, DEPARTING}, "yìn"}, {{IANG, DEPARTING}, "yàng"}, {{ING, DEPARTING}, "yìng"},
	{{IAM, DEPARTING}, "yàm"}, {{IM, DEPARTING}, "yìm"},
	{{U_, DEPARTING}, "wù"}, {{UA, DEPARTING}, "wà"}, {{UO, DEPARTING}, "wò"},
	{{UAI, DEPARTING}, "wài"}, {{UEI, DEPARTING}, "wèi"}, {{UAN, DEPARTING}, "wàn"}, {{UN, DEPARTING}, "wèn"}, {{UANG, DEPARTING}, "wàng"}, {{ONG, DEPARTING}, "wèng"},
	{{IU_, DEPARTING}, "yù"}, {{IUO, DEPARTING}, "yuò"}, {{IUE, DEPARTING}, "yuè"}, {{IUAN, DEPARTING}, "yuàn"}, {{IUN, DEPARTING}, "yùn"}, {{IONG, DEPARTING}, "yòng"},

	{{I_, ENTERING}, "yih"}, {{IA, ENTERING}, "yah"}, {{IE, ENTERING}, "yeh"}, {{IO, ENTERING}, "yoh"},
	{{IAI, ENTERING}, "yaih"}, {{IAU, ENTERING}, "yaoh"}, {{IOU, ENTERING}, "youh"},
	{{U_, ENTERING}, "wuh"}, {{UA, ENTERING}, "wah"}, {{UO, ENTERING}, "woh"},
	{{UAI, ENTERING}, "waih"}, {{UEI, ENTERING}, "weih"},
	{{IU_, ENTERING}, "yuh"}, {{IUO, ENTERING}, "yuoh"}, {{IUE, ENTERING}, "yueh"},
} );

map<pair<RIME, TONE>, cchar*> MarkedPinyin::_mfTrans( {
	{{ZILCH , NEUTRAL}, ""},
	{{A_ , NEUTRAL}, "a"}, {{O_ , NEUTRAL}, "o"}, {{E_ , NEUTRAL}, "e"}, {{EH_ , NEUTRAL}, "ê"},
	{{Y_ , NEUTRAL}, "i"}, {{EL_ , NEUTRAL}, "er"},
	{{AI_ , NEUTRAL}, "ai"}, {{EI_ , NEUTRAL}, "ei"}, {{AU_ , NEUTRAL}, "ao"}, {{OU_ , NEUTRAL}, "ou"},
	{{AN_ , NEUTRAL}, "an"}, {{EN_ , NEUTRAL}, "en"}, {{ANG_ , NEUTRAL}, "ang"}, {{ENG_ , NEUTRAL}, "eng"},
	{{AM_ , NEUTRAL}, "am"}, {{EM_ , NEUTRAL}, "em"},
	{{I_ , NEUTRAL}, "i"}, {{ IA , NEUTRAL}, "ia"}, {{ IE , NEUTRAL}, "ie"}, {{ IO , NEUTRAL}, "io"},
	{{ IAI , NEUTRAL}, "iai"}, {{ IAU , NEUTRAL}, "iao"}, {{ IOU , NEUTRAL}, "iu"},
	{{IAN , NEUTRAL}, "ian"}, {{ IN , NEUTRAL}, "in"}, {{ IANG , NEUTRAL}, "iang"}, {{ ING , NEUTRAL}, "ing"},
	{{ IAM , NEUTRAL}, "iam"}, {{ IM , NEUTRAL}, "im"},
	{{U_ , NEUTRAL}, "u"}, {{ UA , NEUTRAL}, "ua"}, {{ UO , NEUTRAL}, "uo"},
	{{ UAI , NEUTRAL}, "uai"}, {{ UEI , NEUTRAL}, "ui"}, {{ UAN , NEUTRAL}, "uan"}, {{ UN , NEUTRAL}, "un"},
	{{ UEH , NEUTRAL}, "ue"},
	{{UANG , NEUTRAL}, "uang"}, {{ ONG , NEUTRAL}, "ong"},
	{{IU_ , NEUTRAL}, "ü"}, {{ IUO , NEUTRAL}, "üo"}, {{ IUE , NEUTRAL}, "üe"},
	{{ IUAN , NEUTRAL}, "üan"}, {{ IUN , NEUTRAL}, "ün"}, {{ IONG , NEUTRAL}, "iong"},

	{{ZILCH , DARK}, ""},
	{{A_ , DARK}, "ā"}, {{O_ , DARK}, "ō"}, {{E_ , DARK}, "ē"}, {{EH_ , DARK}, "êˉ"},
	{{Y_ , DARK}, "ī"}, {{EL_ , DARK}, "ēr"},
	{{AI_ , DARK}, "āi"}, {{EI_ , DARK}, "ēi"}, {{AU_ , DARK}, "āo"}, {{OU_ , DARK}, "ōu"},
	{{AN_ , DARK}, "ān"}, {{EN_ , DARK}, "ēn"}, {{ANG_ , DARK}, "āng"}, {{ENG_ , DARK}, "ēng"},
	{{AM_ , DARK}, "ām"}, {{EM_ , DARK}, "ēm"},
	{{I_ , DARK}, "ī"}, {{ IA , DARK}, "iā"}, {{ IE , DARK}, "iē"}, {{ IO , DARK}, "iō"},
	{{ IAI , DARK}, "iāi"}, {{ IAU , DARK}, "iāo"}, {{ IOU , DARK}, "iū"},
	{{IAN , DARK}, "iān"}, {{ IN , DARK}, "īn"}, {{ IANG , DARK}, "iāng"}, {{ ING , DARK}, "īng"},
	{{ IAM , DARK}, "iām"}, {{ IM , DARK}, "īm"},
	{{U_ , DARK}, "ū"}, {{ UA , DARK}, "uā"}, {{ UO , DARK}, "uō"},
	{{ UAI , DARK}, "uāi"}, {{ UEI , DARK}, "uī"}, {{ UAN , DARK}, "uān"}, {{ UN , DARK}, "ūn"},
	{{ UEH , DARK}, "uē"},
	{{UANG , DARK}, "uāng"}, {{ ONG , DARK}, "ōng"},
	{{IU_ , DARK}, "ǖ"}, {{ IUO , DARK}, "üō"}, {{ IUE , DARK}, "üē"},
	{{ IUAN , DARK}, "üān"}, {{ IUN , DARK}, "ǖn"}, {{ IONG , DARK}, "iōng"},

	{{A_ , LIGHT}, "á"}, {{O_ , LIGHT}, "ó"}, {{E_ , LIGHT}, "é"}, {{EH_ , LIGHT}, "êˊ"},
	{{Y_ , LIGHT}, "í"}, {{EL_ , LIGHT}, "ér"},
	{{AI_ , LIGHT}, "ái"}, {{EI_ , LIGHT}, "éi"}, {{AU_ , LIGHT}, "áo"}, {{OU_ , LIGHT}, "óu"},
	{{AN_ , LIGHT}, "án"}, {{EN_ , LIGHT}, "én"}, {{ANG_ , LIGHT}, "áng"}, {{ENG_ , LIGHT}, "éng"},
	{{AM_ , LIGHT}, "ám"}, {{EM_ , LIGHT}, "ém"},
	{{I_ , LIGHT}, "í"}, {{ IA , LIGHT}, "iá"}, {{ IE , LIGHT}, "ié"}, {{ IO , LIGHT}, "ió"},
	{{IAI , LIGHT}, "iái"}, {{ IAU , LIGHT}, "iáo"}, {{ IOU , LIGHT}, "iú"},
	{{IAN , LIGHT}, "ián"}, {{ IN , LIGHT}, "ín"}, {{ IANG , LIGHT}, "iáng"}, {{ ING , LIGHT}, "íng"},
	{{IAM , LIGHT}, "iám"}, {{ IM , LIGHT}, "ím"},
	{{U_ , LIGHT}, "ú"}, {{ UA , LIGHT}, "uá"}, {{ UO , LIGHT}, "uó"},
	{{UAI , LIGHT}, "uái"}, {{ UEI , LIGHT}, "uí"}, {{ UAN , LIGHT}, "uán"}, {{ UN , LIGHT}, "ún"},
	{{UEH , LIGHT}, "ué"},
	{{UANG , LIGHT}, "uáng"}, {{ ONG , LIGHT}, "óng"},
	{{IU_ , LIGHT}, "ǘ"}, {{ IUO , LIGHT}, "üó"}, {{ IUE , LIGHT}, "üé"},
	{{ IUAN , LIGHT}, "üán"}, {{ IUN , LIGHT}, "ǘn"}, {{ IONG , LIGHT}, "ióng"},

	{{A_ , RISING}, "ǎ"}, {{O_ , RISING}, "ǒ"}, {{E_ , RISING}, "ě"}, {{EH_ , RISING}, "êˇ"},
	{{Y_ , RISING}, "ǐ"}, {{EL_ , RISING}, "ěr"},
	{{AI_ , RISING}, "ǎi"}, {{EI_ , RISING}, "ěi"}, {{AU_ , RISING}, "ǎo"}, {{OU_ , RISING}, "ǒu"},
	{{AN_ , RISING}, "ǎn"}, {{EN_ , RISING}, "ěn"}, {{ANG_ , RISING}, "ǎng"}, {{ENG_ , RISING}, "ěng"},
	{{AM_ , RISING}, "ǎm"}, {{EM_ , RISING}, "ěm"},
	{{I_ , RISING}, "ǐ"}, {{ IA , RISING}, "iǎ"}, {{ IE , RISING}, "iě"}, {{ IO , RISING}, "iǒ"},
	{{ IAI , RISING}, "iǎi"}, {{ IAU , RISING}, "iǎo"}, {{ IOU , RISING}, "iǔ"},
	{{IAN , RISING}, "iǎn"}, {{ IN , RISING}, "ǐn"}, {{ IANG , RISING}, "iǎng"}, {{ ING , RISING}, "ǐng"},
	{{ IAM , RISING}, "iǎm"}, {{ IM , RISING}, "ǐm"},
	{{U_ , RISING}, "ǔ"}, {{ UA , RISING}, "uǎ"}, {{ UO , RISING}, "uǒ"},
	{{ UAI , RISING}, "uǎi"}, {{ UEI , RISING}, "uǐ"}, {{ UAN , RISING}, "uǎn"}, {{ UN , RISING}, "ǔn"},
	{{ UEH , RISING}, "uě"},
	{{UANG , RISING}, "uǎng"}, {{ ONG , RISING}, "ǒng"},
	{{IU_ , RISING}, "ǚ"}, {{ IUO , RISING}, "üǒ"}, {{ IUE , RISING}, "üě"},
	{{ IUAN , RISING}, "üǎn"}, {{ IUN , RISING}, "ǚn"}, {{ IONG , RISING}, "iǒng"},

	{{A_ , DEPARTING}, "à"}, {{O_ , DEPARTING}, "ò"}, {{E_ , DEPARTING}, "è"}, {{EH_ , DEPARTING}, "êˋ"},
	{{Y_ , DEPARTING}, "ì"}, {{EL_ , DEPARTING}, "èr"},
	{{AI_ , DEPARTING}, "ài"}, {{EI_ , DEPARTING}, "èi"}, {{AU_ , DEPARTING}, "ào"}, {{OU_ , DEPARTING}, "òu"},
	{{AN_ , DEPARTING}, "àn"}, {{EN_ , DEPARTING}, "èn"}, {{ANG_ , DEPARTING}, "àng"}, {{ENG_ , DEPARTING}, "èng"},
	{{AM_ , DEPARTING}, "àm"}, {{EM_ , DEPARTING}, "èm"},
	{{I_ , DEPARTING}, "ì"}, {{ IA , DEPARTING}, "ià"}, {{ IE , DEPARTING}, "iè"}, {{ IO , DEPARTING}, "iò"},
	{{ IAI , DEPARTING}, "iài"}, {{ IAU , DEPARTING}, "iào"}, {{ IOU , DEPARTING}, "iù"},
	{{IAN , DEPARTING}, "iàn"}, {{ IN , DEPARTING}, "ìn"}, {{ IANG , DEPARTING}, "iàng"}, {{ ING , DEPARTING}, "ìng"},
	{{ IAM , DEPARTING}, "iàm"}, {{ IM , DEPARTING}, "ìm"},
	{{U_ , DEPARTING}, "ù"}, {{ UA , DEPARTING}, "uà"}, {{ UO , DEPARTING}, "uò"},
	{{ UAI , DEPARTING}, "uài"}, {{ UEI , DEPARTING}, "uì"}, {{ UAN , DEPARTING}, "uàn"}, {{ UN , DEPARTING}, "ùn"},
	{{ UEH , DEPARTING}, "uè"},
	{{UANG , DEPARTING}, "uàng"}, {{ ONG , DEPARTING}, "òng"},
	{{IU_ , DEPARTING}, "ǜ"}, {{ IUO , DEPARTING}, "üò"}, {{ IUE , DEPARTING}, "üè"},
	{{ IUAN , DEPARTING}, "üàn"}, {{ IUN , DEPARTING}, "ǜn"}, {{ IONG , DEPARTING}, "iòng"},

	{{A_ , ENTERING}, "ah"}, {{O_ , ENTERING}, "oh"}, {{E_ , ENTERING}, "eh"}, {{EH_ , ENTERING}, "êh"},
	{{Y_ , ENTERING}, "ih"},
	{{AI_ , ENTERING}, "aih"}, {{EI_ , ENTERING}, "eih"}, {{AU_ , ENTERING}, "aoh"}, {{OU_ , ENTERING}, "ouh"},
	{{I_ , ENTERING}, "ih"}, {{ IA , ENTERING}, "iah"}, {{ IE , ENTERING}, "ieh"}, {{ IO , ENTERING}, "ioh"},
	{{ IAU , ENTERING}, "iaoh"}, {{ IOU , ENTERING}, "iuh"},
	{{U_ , ENTERING}, "uh"}, {{ UA , ENTERING}, "uah"}, {{ UO , ENTERING}, "uoh"},
	{{ UAI , ENTERING}, "uaih"}, {{ UEI , ENTERING}, "uih"},
	{{ UEH , ENTERING}, "ueh"},
	{{IU_ , ENTERING}, "üh"}, {{ IUO , ENTERING}, "üoh"}, {{ IUE , ENTERING}, "üeh"}

} );
}//end cphonetic
